services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: aira-frontend-container
    ports:
      - "5173:80"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: aira-backend-container
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}